config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#index"
  resources :cars, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :favourites, only: [:create]
  end

  resources :favourites, only: [:index, :destroy]
  resources :pages, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :reviews
  has_many :favourites

  validates :brand, :model, :fuel, presence: true
  validates :year, presence: true, format: { with: /\A(19|20)\d{2}\z/, message: 'must be a valid year' }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars
  validates :nickname, presence: true, uniqueness: true, format: { with: /([a-zA-Z0-9]+[_-])*/,  message: "can only contain letters, numbers, underscores, or hyphens"  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :rating, presence: true, inclusion: { in: 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @review = Review.new
    @favourite = Favourite.new
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @favourites = Favourite.all
  end

  def create
    @car = Car.find(params[:car_id])
    @favourite = Favourite.new
    @favourite.car = @car

    if @favourite.save
      redirect_to car_path(@car), notice: 'Added to garage!'
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    redirect_to favourites_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @car = Car.find(params[:car_id])
    @review.car = @car

    if @review.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/_car.html.erb
<%= link_to car_path(car), class: "card-car-link" do %>
  <div class="card-car">

    <div class="card-car-infos">
      <div class="card-content">
        <h2><%= car.brand %></h2>
        <h4><%= car.model %></h4>
        <p><%= car.created_at.strftime("%A %B %e at %l:%M%P") %></p>
      </div>

    <div class="car-image">
      <%= image_tag(car.img_url) if car.img_url.present? %>

      <div id="owner">
        <p><%= car.owner.nickname %></p>
      </div>
    </div>
      <div id="card-car-comment">
        <h4><i class="fa-regular fa-comment"></i> Comment</h4>
      </div>
    </div>
  </div>
<% end %>

app/views/cars/index.html.erb
<div class="cars-index">
  <%= render @cars %>
</div>

app/views/cars/show.html.erb
<div class="car-show-page">
  <div class="car-card">
    <div class="car-image-container">
      <div class="car-image">
        <%= image_tag @car.img_url, alt: "#{@car.brand} #{@car.model}" %>
      </div>

      <div class="save-link-container">
        <% if @car.favourites.empty? %>
          <%= simple_form_for [@car, @favourite] do |f| %>
            <%= f.submit 'Save in my garage', class: 'save-garage-btn' %>
          <% end %>
        <% else %>
          <p class="already-garage">This car is already in your garage</p>
        <% end %>
      </div>
    </div>

    <div class="car-card-content">
      <div class="car-info">
        <h2><%= @car.brand %></h2>
        <h3><%= @car.model %></h3>
        <p><%= @car.fuel %></p>
        <p><%= @car.year %></p>
      </div>

      <div class="review-form">
        <%= simple_form_for([@car, @review]) do |f| %>
          <%= f.input :comment, placeholder: "Comment here...", label: false %>
          <%= f.input :rating, collection: 1..5, label: false %>
          <%= f.submit "Send", class: "send-btn" %>
        <% end %>
      </div>
    </div>

    <div class="review-list">
      <% @car.reviews.each do |review| %>
        <div class="review">
          <p><%= review.comment %></p>
          <p class="stars"><%= '⭐️' * review.rating %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/favourites/index.html.erb
<h3> My Garage </h3>

<% if @favourites.any? %>
  <div>
    <% @favourites.each do |favourite| %>
      <div class="favourite-card">

        <div class="card-garage">
        <div class="car-image-wrapper">
          <%= image_tag favourite.car.img_url, alt: "#{favourite.car.brand} #{favourite.car.model}", class: "car-image" %>
          </div>
          <div class="card-garage-infos">
            <h5><%= favourite.car.brand %></h5>
            <h6><%= favourite.car.model %></h6>
             <p><%= favourite.car.year %> | <%= favourite.car.fuel %></p>
          </div>
        <%= link_to favourite_path(favourite), class: "bin", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
        </div>

      </div>
    <% end %>
  </div>
<% else %>
  <p>You have no cars in your garage yet.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAwesomeGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <%= yield %>

  </body>
</html>

app/views/pages/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://cdn.mos.cms.futurecdn.net/Xq9HRd3Nh9uGNQvvVXeVZE.jpg);">
  <div class="container">
    <h1>Awesome Garage</h1>
    <p>Your personal garage with the cars of your dreams</p>
    <%= link_to "Enter", cars_path, class: "btn btn-primary"%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light navbar-lewagon">
  <div class="container-fluid d-flex justify-content-between align-items-center w-100">
    <%= link_to root_path, class: "navbar-brand d-flex align-items-center gap-2" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", alt: "Logo", height: 30 %>
      <h2 class="mb-0">Awesome Garage</h2>
    <% end %>

    <div class="d-flex gap-4">
      <%= link_to "Home", root_path, class: "nav-link" %>
      <%= link_to "My Garage", favourites_path, class: "nav-link" %>
    </div>
  </div>
</div>